
default:
  image: python:3

stages:
  - lint
  - test

  
isort:
  stage: lint
  before_script:
    - pip install isort
  script:
    - isort --check-only --skip-glob=.tox --reverse-sort --profile=black .
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[do-not-lint\]/
  artifacts:
    when: always


black:
  stage: lint
  before_script:
    - pip install blue
  script:
    - blue --check .
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[do-not-lint\]/
  artifacts:
    when: always


flake8: 
  stage: lint
  before_script:
    - pip install flake8
  script:
    - flake8 --exclude='.tox' --exclude='__init__.py' --extend-exclude='*_pb2*.py' .

  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[do-not-lint\]/
  artifacts:
    when: always


test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test .
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[do-not-test\]/
  artifacts:
    when: always
